name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

jobs:
  frontend:
    name: Frontend Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.24
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Test
        run: bun run test
      - name: Build
        run: |
          cd frontend
          bun install
          bun run build

  backend:
    name: Backend Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Go Mod Download
        working-directory: backend
        run: go mod download
      - name: Go Vet
        working-directory: backend
        run: go vet ./...
      - name: Go Test
        working-directory: backend
        env:
          GOCACHE: ${{ github.workspace }}/backend/.cache
        run: go test ./...

  e2e:
    name: Playwright E2E
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Placeholder
        run: echo "TODO: Implement Playwright E2E suite (T017)"

  load:
    name: k6 Load Test
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Placeholder
        run: echo "TODO: Implement k6 load test (T019)"
